version: '3'

services:
  cl_jobs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro
      - ./.env:/app/.env:ro
    restart: always
    environment:
      - SCHEDULER_INTERVAL_MINUTES=${SCHEDULER_INTERVAL_MINUTES:-15}
      - DOCKER_CONTAINER=true
    # Run the scheduler that will execute cl_jobs.py at specified intervals
    command: ["python", "cl_job_scheduler.py", "--run-now"]

  slack_manager:
    build:
      context: .
      dockerfile: Dockerfile.slack
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro
      - ./.env:/app/.env:ro
    restart: unless-stopped
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SLACK_AUTHORIZED_USERS=${SLACK_AUTHORIZED_USERS}
      - EMAIL=${EMAIL}
      - PASSWORD_0=${PASSWORD_0}
      - PASSWORD_1=${PASSWORD_1}
      # Add additional environment variables as needed

  # Optional Vault service
  vault:
    image: hashicorp/vault:1.15.2
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-only-token
    volumes:
      - vault-data:/vault/data
    command: server -dev -dev-root-token-id=dev-only-token

  # Vault client for interacting with secrets
  vault-client:
    build:
      context: .
      dockerfile: Dockerfile.vault-client
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
    depends_on:
      - vault

volumes:
  vault-data: