FROM python:3.9-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir hvac python-dotenv

COPY vault-client.py /app/
# .env will be mounted via volume

# Set entrypoint
ENTRYPOINT ["python", "vault-client.py"]